name: Playwright Table Sum (Python)

on:
  push:
    branches: [ main ]

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Scraper - 24f1001980@ds.study.iitm.ac.in
        run: python scrape.py
